version: "3.7"

services: 
  db_case_fortbrasil:
    image: postgres
    container_name: db_case_fortbrasil
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=casefortbrasil
      - POSTGRES_PASSWORD=qwer1q2w3e4r
      - POSTGRES_DB=casefortbrasil
    volumes: 
      - ~/home/andrey/Documentos/Dev/Docker/database/case_fortbrasil_timesheet:/var/lib/postgres
  api_case_fortbrasil:
    build: .
    container_name: api_case_fortbrasil
    restart: always
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
